#!/bin/bash

export LDFLAGS="${LDFLAGS} -lrt"

./waf configure --verbose --prefix=${PREFIX}

cat <<EOF > build/release/config/package_revision_autogenerated.hpp
#ifndef PACKAGE_REVISION_HPP
#define PACKAGE_REVISION_HPP
namespace globals {
char const* const package_version = "2.2.0" ;
char const* const package_revision = "unknown" ;
}
#endif
EOF

./waf build --verbose --jobs=$(nproc)

./waf install --verbose

for i in ${PREFIX}/bin; do

    ln -s \
        $(basename ${i}) \
        $(echo $i | rev | cut -d_ -f2- | rev)

done
