package:
  name: gcta
  version: 1.94.1

source:
  - git_url: https://github.com/jianyangqt/gcta
    git_rev: v1.94.1
    folder: gcta
    patches:
      - patches/0001-simu-seed.patch
  - git_url: https://github.com/yixuan/spectra
    git_rev: v1.0.1
    folder: spectra

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
  host:
    - boost-cpp
    - cmake
    - eigen
    - gsl
    - make
    - mkl
    - mkl-include
    - sqlite
    - zlib
  run:
    - gsl
    - mkl
    - zlib

test:
  commands:
    - gcta64 | grep "Analysis started"

about:
  home: "https://cnsgenomics.com/software/gcta/"
  license: MIT
  summary: GCTA (Genome-wide Complex Trait Analysis) estimates the proportion of phenotypic variance explained by all genome-wide SNPs for complex traits.

extra:
  identifiers:
    - biotools:gcta
    - doi:10.1016/j.ajhg.2010.11.011
