# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: "3.12"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-ast
      - id: check-symlinks
      - id: mixed-line-ending
      - id: check-case-conflict
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        exclude_types:
          - diff
      - id: end-of-file-fixer
        exclude_types:
          - diff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.1
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        types_or: [python, rst, markdown]
  - repo: https://github.com/MarcoGorelli/cython-lint
    rev: v0.16.2
    hooks:
      - id: cython-lint
      - id: double-quote-cython-strings
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        additional_dependencies:
          - numpy
          - pandas-stubs
          - types-psutil
          - types-PyYAML
          - types-seaborn
          - types-setuptools
          - types-tqdm
          - universal_pathlib
