package:
  name: c-blosc2
  version: 2.14.5.dev0

source:
  git_url: https://github.com/Blosc/c-blosc2
  git_rev: fb5be70daa212a6a61343a185adfb5659e5247ae

build:
  run_exports:
    - "{{ pin_subpackage('c-blosc2', max_pin='x.x') }}"

requirements:
  build:
    - cmake
    - make  # [unix]
    - "{{ compiler('c') }}"
    - "{{ compiler('cxx') }}"
  host:
    - lz4-c
    - zstd x.x
    - zlib-ng

test:
  commands:
    - test -e $PREFIX/include/blosc2.h                    # [unix]
    - test -e $PREFIX/include/blosc2/blosc2-export.h      # [unix]
    - test -e $PREFIX/lib/libblosc2${SHLIB_EXT}           # [unix]
    - test -e $PREFIX/lib/pkgconfig/blosc2.pc             # [unix]

about:
  home: https://github.com/Blosc/c-blosc2
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A simple, compressed, fast and persistent data store library for C

  description: |
    Next generation of C-Blosc library bringing in a new container (schunk) that can optionally be persisted (frame).  Also, more filters, codecs and other bells and whistles like pre-filter support have been added.  The API tries to be as compatible as possible with the original C-Blosc.

extra:
  recipe-maintainers:
    - FrancescAlted
    - hmaarrfk
    - zklaus
