package:
  name: python-blosc2
  version: 2.6.3.dev0

source:
  git_url: https://github.com/Blosc/python-blosc2
  git_rev: 3bc9d1782525808af0fdddd4399ffd79e29797ce

requirements:
  build:
    - "{{ compiler('c') }}"
    - "{{ compiler('cxx') }}"
    - cmake
    - make # [unix]
    - ninja
    - pkg-config
  host:
    - c-blosc2 >=2.14.5.dev0
    - cython
    - numpy
    - pathlib
    - python
    - python-build
    - scikit-build
    - setuptools
  run:
    - python
    - msgpack-python
    - ndindex >=1.4
    - py-cpuinfo
    - numexpr
    - httpx

test:
  imports:
    - blosc2
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Blosc/python-blosc2
  license_family: BSD
  license: BSD-3-Clause
  license_file: LICENSE.txt
  dev_url: https://github.com/Blosc/python-blosc2
  doc_url: https://www.blosc.org/python-blosc2/python-blosc2.html
  summary: A Python wrapper for the extremely fast Blosc2 compression library

extra:
  recipe-maintainers:
    - FrancescAlted
    - goanpeca
    - martaiborra
