package:
  name: python-blosc2
  version: 2.2.4

source:
  git_url: https://github.com/Blosc/python-blosc2
  git_rev: v2.2.4
  patches:
    - 0001-expose-cmake-use-system-blosc2.patch

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - make
    - pkg-config
  host:
    - c-blosc2
    - "cython<1"
    - "numpy>=1.20.3"
    - pip
    - "python>=3.11"
    - scikit-build
    - setuptools
    - wheel
  run:
    - "python>=3.11"
    - msgpack-python
    - "ndindex>=1.4"
    - "numpy>=1.20.3"
    - py-cpuinfo
    - rich

test:
  requires:
    - psutil
    - pytest
    - pytorch
  source_files:
    - tests/
    - pytest.ini
  imports:
    - blosc2
  commands:
    - python -c "import blosc2; blosc2.print_versions()"
    - python -m pytest

about:
  home: https://github.com/Blosc/python-blosc2
  license_family: BSD
  license: BSD-3-Clause
  license_file: LICENSE.txt
  dev_url: https://github.com/Blosc/python-blosc2
  doc_url: https://www.blosc.org/python-blosc2/python-blosc2.html
  summary: A Python wrapper for the extremely fast Blosc2 compression library
