package:
  name: raremetal
  version: 4.15.1

source:
  git_url: https://github.com/statgen/raremetal
  git_depth: 1

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("fortran") }}
    - openmp
  host:
    - cget
    - cmake
    - curl
    - make
    - zlib
  run: []

test:
  commands:
    - test $(raremetal | wc -w) -gt 0
    - test $(raremetalworker | wc -w) -gt 0

about:
  home: https://github.com/statgen/raremetal
