[project]
name = "gwas"
dynamic = ["version"]

requires-python = ">=3.11"

dependencies = ["numpy", "pandas", "torch<2", "scipy", "threadpoolctl"]

[project.scripts]
gwas = "gwas.cli:main"

[build-system]
requires = [
  "cython>=3b1",
  "numpy",
  "setuptools>=62",
  "setuptools_scm[toml]>=6.2",
  "wheel",
]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
test = ["pytest", "pytest-benchmark"]

[tool.isort]
line_length = 88
profile = "black"

[tool.pylint.format]
max-line-length = "88"

[tool.setuptools_scm]
version_scheme = "no-guess-dev"
root = "../../"
