[project]
name = "gwas"
dynamic = ["version"]

requires-python = ">=3.11"

dependencies = [
  "numpy>=1.22",
  "scipy",
  "pandas",
  "matplotlib",
  "seaborn",
  "torch<2",
  "networkx",
  "psutil",
  "threadpoolctl",
  "tqdm",
  "pyyaml",
  "more-itertools",
  "typing_extensions",
]

[project.scripts]
score = "gwas.score.cli:main"
stratify = "gwas.stratify.cli:main"

[build-system]
requires = [
  "cython>=3b1",
  "numpy",
  "setuptools>=62",
  "setuptools_scm[toml]>=6.2",
  "wheel",
]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
test = ["pytest", "pytest-benchmark"]

[tool.isort]
line_length = 88
profile = "black"

[tool.pylint.format]
max-line-length = "88"

[tool.setuptools_scm]
version_scheme = "no-guess-dev"
root = "../../"
