package:
  name: raremetal-debug
  version: 4.15.1

source:
  git_url: https://github.com/statgen/raremetal
  git_depth: 1
  patches:
    - ../raremetal/0001-fix-build-gcc-13.patch
    - ../raremetal/0002-fix-rmath.patch
    - 0003-debug-print.patch

requirements:
  build:
    - "{{ compiler('c') }}"
    - "{{ compiler('cxx') }}"
    - "{{ compiler('fortran') }}"
    - openmp
  host:
    - cget
    - cmake
    - curl
    - make
    - zlib
  run: []

test:
  commands:
    - test $(raremetal-debug | wc -w) -gt 0
    - test $(raremetalworker-debug | wc -w) -gt 0

about:
  home: https://github.com/statgen/raremetal
