package:
  name: gwas
  version: 0.1.0

source:
  git_url: ../..

requirements:
  build:
    - "{{ compiler('c') }}"
    - "{{ compiler('cxx') }}"
    # - "{{ compiler('rust') }}"
    - "sysroot_linux-64>=2.17"
  host:
    - "python>=3.12"
    - "cython>=3b1"
    - mkl
    - mkl-include
    - "numpy>=1.22"
    - "python"
    - pip
    - "setuptools>=62"
    - "setuptools_scm>=6.2"
    - wheel
    - zlib
    - htslib
    - c-blosc2
    - python-blosc2
  run:
    - python
    # python dependencies
    - ipython
    - "numpy>=1.22"
    - scipy
    - pandas
    - matplotlib
    - seaborn
    - polars
    - "python-flatbuffers"
    - psutil
    - rpy2
    - threadpoolctl
    - tqdm
    - pyyaml
    - mkl
    - universal_pathlib
    - more-itertools
    - tabulate
    - adjusttext
    # linear algebra
    - jax
    - jaxtyping
    - chex
    - optax
    - etils
    - importlib_resources
    # compression tools
    - zstd
    - htslib
    - xz
    - bzip2
    - lz4-c
    - python-blosc2
    - pyarrow
    # genetics tools
    - bcftools >=1.17
    - gcta
    - ldsc
    - metal
    - plink
    - plink2
    - raremetal
    - tabix
    # transfer tools
    - upload
    - sshfs

test:
  imports:
    - gwas
  commands:
    - score 2>&1 | grep usage
