package:
  name: gwas
  version: 0.1.0

source:
  git_url: ../..

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("rust") }}
    - "sysroot_linux-64>=2.17"
  host:
    - python
    - "cython>=3b1"
    - mkl
    - mkl-include
    - "numpy>=1.22"
    - "python"
    - pip
    - "setuptools>=62"
    - "setuptools_scm>=6.2"
    - "setuptools-rust"
    - wheel
    - zlib
  run:
    - python
    # Python dependencies
    - "numpy>=1.22"
    - scipy
    - pandas
    - matplotlib
    - seaborn
    - "pytorch<2"
    - networkx
    - psutil
    - threadpoolctl
    - tqdm
    - pyyaml
    - more-itertools
    - typing_extensions
    - mkl
    # Compression tools
    - zstd
    - htslib
    - xz
    - bzip2
    - lz4-c

test:
  commands:
    - test $(gwas 2>&1 | wc -w) -gt 0
