package:
  name: dosage-convertor
  version: 1.0.4

source:
  git_url: https://github.com/Santy-8128/DosageConvertor
  patches:
    - patches/0001-version.patch
    - patches/0002-libstatgen.patch

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
  host:
    - cget
    - cmake
    - curl
    - make
    - zlib
  run: []

test:
  commands:
    - test $(DosageConvertor | wc -w) -gt 0

about:
  home: https://genome.sph.umich.edu/wiki/DosageConvertor
