package:
  name: r-gmmat
  version: 1.3.2

source:
  git_url: https://github.com/hanchenphd/GMMAT
  git_depth: 1

build:
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
  host:
    - libblas
    - liblapack
    - r-base >=4.0
    - r-compquadform
    - r-foreach
    - r-matrix
    - r-rcpp
    - r-rcpparmadillo >=0.10.7.5
    - bioconductor-seqarray
    - bioconductor-seqvartools
  run:
    - r-base >=4.0
    - r-compquadform
    - r-foreach
    - r-matrix
    - r-rcpp
    - bioconductor-seqarray
    - bioconductor-seqvartools

test:
  commands:
    - $R -e "library(\"GMMAT\")"

about:
  home: https://github.com/hanchenphd/GMMAT
  license: GNU GPL
  license_family: GPL3
