package:
  name: ldsc
  version: 2.0.2

source:
  url: "https://github.com/belowlab/ldsc/archive/refs/tags/2.0.2.tar.gz"
  sha256: "f28c2fc77c05aa59f293e2666ba38a69610b8e153ff3b7f382dec53601bebc71"

build:
  noarch: python
  script: |
    nosetests --exclude="test_nextSNPs|test_nextSNPs_maf_ref|test_get_compression_gzip"
    {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
    - pynose
    - bitarray >=2.6.0
    - pybedtools >0.9.1
    - scipy >=1.9.2
    - numpy >=1.23.3
    - pandas >=1.5.0
  run:
    - python
    - bitarray >=2.6.0
    - pybedtools >0.9.1
    - scipy >=1.9.2
    - numpy >=1.23.3
    - pandas >=1.5.0

test:
  imports:
    - ldscore.ldscore
  commands:
    - make_annot.py --help 2>&1 | grep usage
    - munge_sumstats.py --help 2>&1 | grep usage
    - ldsc.py --help 2>&1 | grep usage

about:
  home: http://github.com/bulik/ldsc
  summary: LD Score Regression (LDSC)
  license: GPL-3.0
  license_file: LICENSE
