{% set version = "4.1.3" %}

package:
  name: r-mathlib
  version: {{ version }}

source:
  svn_url: https://svn.r-project.org/R/tags/R-{{ version.replace('.', '-') }}

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
  host:
    - bzip2
    - libblas
    - liblapack
    - pcre2
    - xz
    - zlib
  run: []

test:
  commands: []
