
package:
  name: upload
  version: 0.5.10

source:
  url: "https://github.com/hippocampusgirl/upload/archive/v0.5.10.tar.gz"
  sha256: "29a097cb8bdccf9ef672e8ba160a12650aabf40f9f9c3f56b32ab5b8b81599cd"

build:
  noarch: generic

requirements:
  build:
    - "{{ compiler('c') }}"
    - "{{ compiler('cxx') }}"
    - nodejs
    - make
  host:
    - nodejs
  run:
    - nodejs

test:
  requires:
    - nodejs
  commands:
    - upload --help

about:
  home: https://github.com/hippocampusgirl/upload
