
package:
  name: upload
  version: 0.5.12

source:
  git_url: https://github.com/hippocampusgirl/upload
  git_rev: v0.5.12

build:
  noarch: generic

requirements:
  build:
    - "{{ compiler('c') }}"
    - "{{ compiler('cxx') }}"
    - nodejs
    - make
  host:
    - nodejs
  run:
    - nodejs

test:
  requires:
    - nodejs
  commands:
    - upload --help

about:
  home: https://github.com/hippocampusgirl/upload
