
package:
  name: upload
  version: 0.5.5

source:
  url: "https://github.com/hippocampusgirl/upload/archive/v0.5.5.tar.gz"
  sha256: 7def6f41395fef10b931181d245d74762119723dd795eb3ebeb530adeef24c3d

build:
  noarch: generic

requirements:
  build:
    - "{{ compiler('c') }}"
    - "{{ compiler('cxx') }}"
    - nodejs
    - make
  host:
    - nodejs
  run:
    - nodejs

test:
  requires:
    - nodejs
  commands:
    - upload --help

about:
  home: https://github.com/hippocampusgirl/upload
