# Adapted from https://github.com/bioconda/bioconda-recipes/blob/227f6256b60f6acd29c6307aa7ac51d1cc21a524/recipes/r-saige/meta.yaml

package:
  name: r-saige
  version: 1.1.6

source:
  git_url: https://github.com/saigegit/SAIGE
  git_rev: 13892c8bd88f7bebef3fd5ecd5ba98951b53b9a3
  patches:
    - patches/0001-use-shared-libs-in-makevars.patch

build:
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
  host:
    - boost-cpp
    - libblas
    - liblapack
    - superlu
    - savvy
    - zstd
    - zlib
    - r-base >=4.0
    - r-bh
    - r-data.table
    - r-devtools
    - r-dplyr
    - r-dbplyr
    - r-ellipsis
    - r-matrix
    - r-optparse
    - r-qlcmatrix
    - r-rcpp
    - r-rcpparmadillo >=0.10.7.5
    - r-rcppeigen
    - r-rcppparallel
    - r-rhpcblasctl
    - r-roxygen2
    - r-rversions
    - r-r.utils
    - r-rsqlite
    - r-spatest
    - r-skat
    - r-metaskat
    - r-vctrs
  run:
    - r-base
    - boost-cpp
    - savvy
    - r-data.table
    - r-dplyr
    - r-dbplyr
    - r-matrix
    - r-optparse
    - r-rcpp
    - r-rcppparallel
    - r-rhpcblasctl
    - r-spatest
    - r-rsqlite

test:
  commands:
    - $R -e "library(\"SAIGE\")"
    - step1_fitNULLGLMM.R --help
    - step2_SPAtests.R --help
    - createSparseGRM.R --help
    - extractNglmm.R --help

about:
  home: https://github.com/saigegit/SAIGE
  license: GNU GPL
  license_family: GPL3
  license_file: LICENSE
  summary: SAIGE is an R package with Scalable and Accurate Implementation of Generalized mixed model (Chen, H. et al. 2016)
  description: |
    SAIGE is an R package with Scalable and Accurate Implementation of Generalized
    mixed model (Chen, H. et al. 2016). It accounts for sample relatedness and is
    feasible for genetic association tests in large cohorts and biobanks (N > 400000).
