# Adapted from https://github.com/bioconda/bioconda-recipes/blob/master/recipes/bolt-lmm/meta.yaml

package:
  name: bolt-lmm
  version: 2.4.1

source:
  url: https://storage.googleapis.com/broad-alkesgroup-public/BOLT-LMM/downloads/BOLT-LMM_v2.4.1.tar.gz
  patches:
    - patches/0001-makefile.patch

requirements:
  build:
    - make
    - {{ compiler("cxx") }}
  host:
    - boost-cpp
    - "mkl<2023"
    - mkl-include
    - nlopt
    - zlib
    - zstd
  run:
    - boost-cpp
    - mkl
    - nlopt
    - zlib
    - zstd

test:
  commands:
    - bolt --help | grep "BOLT-LMM"

about:
  home: https://alkesgroup.broadinstitute.org/BOLT-LMM/
  license: GPL-3+
  summary: Efficient large cohorts genome-wide Bayesian mixed-model association testing

extra:
  identifiers:
    - doi:10.1038/ng.3190
